### ISSUE TITLE
Merge stream delay

### ISSUE THREAD

**Issue by meepeek** [paldepind/flyd#185] opened 2018-08-25 21:34 UTC
As the following code:
```
const mixStream = flyd.merge(stream1, stream2)

const mixScan = flyd.scan((o, n) => { return {
  a: scanStream1(),
  b: scanStream2()
} }, {
  a: 0,
  b: 0
}, mixStream)
```
I expect mixScan to show the result from both stream 1 and 2 updates. I did, but with a 1 step behind. Given stream1 <-- [1,2,3] then stream2 [4,5,6], this is the result for mixScan

| mixScan  | stream1 | stream2 |
| --------- | -------- | --------- |
| {a:0, b:0} |               |                  |
| {a:0, b:0} | 1 |
{a:1, b:0} | 2 |
{a:2, b:0} | 3 |
{a:3, b:0} | |  4
{a:3, b:4} | | 5
{a:3, b:5}  | |                    6

Please find https://github.com/meepeek/meiosis-react-example for working example

**Comment by nordfjord** [comment] 2018-08-29 12:31
Hey @meepeek Thank you for the issue.

I'm not sure I quite follow your text though, perhaps you could clarify a few things for me.

Is this bin not as expected: https://jsbin.com/fonoyituga/edit?html,js,output

?

**Comment by nordfjord** [comment] 2018-08-29 12:33
![2018-08-29-123252_1921x647_scrot](https://user-images.githubusercontent.com/3721521/44787813-b3c88e00-ab87-11e8-842c-9634f27b8a7c.png)

**Comment by meepeek** [comment] 2018-08-30 04:29
![screen shot 2561-08-30 at 11 23 40](https://user-images.githubusercontent.com/2456033/44829459-37957f80-ac47-11e8-87f5-0762610c384f.png)

I followed your link but cannot get the output.

Could you clone https://github.com/meepeek/meiosis-react-example then run ? You will see that clicking buttons in the example and the state tracer for mixListener (scanner) would lag behind 1 step, but tapping the tracer for each individual streams work just fine.

**Comment by nordfjord** [comment] 2018-08-30 10:50
I honestly don't have the time to do that currently.

But if you can provide me a minimal flyd only reproducible issue, then I'd be happy to take a look.

also it seems you were routed to some strange url, this is the link to the bin: https://jsbin.com/bazibuzobu/edit?html,js,output

Feel free to use it as a baseline for your own reproducible case.

**Comment by nordfjord** [comment] 2018-08-30 21:03
Okay I looked at your App.jsx file since I happened to have time.

https://github.com/meepeek/meiosis-react-example/blob/master/src/App.js#L12

Change this line from

```js
```

**Comment by nordfjord** [comment] 2018-08-31 21:52
I take it by the thumbs up this issue is resolved, I'll close it, but feel free to reopen if this did not help.

**Closed by nordfjord** 2018-08-31 21:52 UTC
