### ISSUE TITLE
Extensions in main repository

### ISSUE THREAD

**Issue by iofjuupasli** [paldepind/flyd#32] opened 2015-06-09 14:45 UTC

**Comment by paldepind** [comment] 2015-06-09 15:11
This gives several advantages. With this change modules will be included like this `flyd/module/filter`.

**Comment by jayrbolton** [comment] 2015-09-03 22:43
Would also like this so that I can install one package and require like `var filter = require('flyd/module/filter')`. Are you still in support of this? Would you want to do it with git submodules of each module inside `module/moduleName`? I'm not sure if the submodule approach would work when they all do `require('flyd')` rather than something like `require('../../flyd')`

**Comment by avesus** [comment] 2015-09-04 05:59
Hey, it IS the NPM. There should be different git repositories, i.e.
flyd-filter etc. All of them COULD be included within "main" flyd package.
At early stages for very small code it is POSSIBLE to have all of them in a
single git repo, but most of much productive npm practitioners advice to
split your project into NPM modules (and distinct git repos) ASAP.

Git submodules is a very legacy method. It plays very bad in practice.

At start point, it could be different package.json in each of flyd
"sub"-module directory. You could easily get `npm link` on them to make
"local global" modules. It plays very well, but it requires people to RTFM.
Please, make NPM your friend - I mean not npm repository but npm tool. It
ever allows you to make your own packages referenced as git repos. And much
more. RTFM.

**Comment by paldepind** [comment] 2015-09-05 19:18
I think the advantages are

* Reporting issues is easier due to only one repo
* Managing dependencies is easier
* Creating new modules is easier. No need to create new repository and submit a new package to npm

Note that all Flyd modules are less than 10 lines. I think having them in a single repository is certainly viable.

I think each module should consist of a single file inside a `module` directory. This would give the syntax @jayrbolton describes. I'd then like to have all module documentation inside at single readme in the `module` directory. This will make browsing modules easier.

 Any thoughts?

**Comment by jayrbolton** [comment] 2015-09-05 19:22
I agree, this would be really convenient. I actually have a fork with all the modules inside /module already, without submodules or npm links. I could post a PR in just a sec.

**Comment by avesus** [comment] 2015-09-10 13:34
> - Reporting issues is easier due to only one repo

You could disable issue reporting on each module repo.

> - Managing dependencies is easier

Yup.

> - Creating new modules is easier. No need to create new repository and submit a new package to npm

Authoritarian style. :-)

P.S.: Please, explain me how to do `require('module-name')` without specifying `require('flyd/modules/module-name')`?

**Comment by ericgj** [comment] 2015-09-10 14:52
Question, are you leaving the old npm repos (but not updating them), or removing them from npm? I would prefer leaving them so existing downstream code doesn't break.

**Comment by paldepind** [comment] 2015-09-10 15:01
> Authoritarian style. :-)

No. I will gladly accepts PRs with modules.

> Please, explain me how to do require('module-name') without specifying require('flyd/modules/module-name')?

I don't understand this question. The later is how one would do it.

I don't think you can remove npm repositories. Only deprecate them which I will probably do.

**Comment by avesus** [comment] 2015-09-10 15:49
> No. I will gladly accepts PRs with modules.

Sorry, but you woun't - if... [The Bus Factor](https://en.wikipedia.org/wiki/Bus_factor) happens.

> I don't think you can remove npm repositories. Only deprecate them which I will probably do.

Actually, you could actively support that npm repos. It is not necessary to each npm package has its own distinct git repo. `npm publish` works for subfolders pretty nice (I hope) - but it needs some testing (all of the packages on npm could have a link to the same GitHub repo).

It allows to factor out a lot of dependencies in big complex projects - ever in your small one it could be lot of nano-dependencies.

Placing that dependencies in each `modules/module-name/package.json` is much better than float up them to the main `package.json`.

Ask @sindresorhus how to manage that most effectively!

In such case, both `require('flyd-module-name')` and `require('flyd/modules/module-name')` will work.

> Only deprecate them which I will probably do.

Why deprecate if you could support them all? With a simple script which will do re-publish if a module-subfolder files changed (mind `git diff` and so on).

**Comment by paldepind** [comment] 2015-09-10 15:57
> Sorry, but you woun't - if... The Bus Factor happens.

Sure. Then fork it. Or publish your modules separately. That is still possible. And it is still recommended if your module has dependencies.

I will have to look deeper into the thing you're suggesting.

**Comment by ericgj** [comment] 2015-09-10 16:01
I don't see what the problem is with `require('flyd/module/name')` ?  It certainly saves the administrative work of having to maintain separate package.json's (or the work to script it). We are talking about 10-20 line functions at most, why add admin overhead?  Deprecating the separate npm packages seems sane to me.

**Comment by avesus** [comment] 2015-09-10 16:02
> I will gladly accepts PRs with modules.

Modularity and your very high level of acceptance are basic reasons people start use your code and not other's. I'm very impressed with your [snabbdom](https://github.com/paldepind/snabbdom)! Please, consider that a lot of people don't understand, dislike or just think that it is very complex/very slow to use the Functional Reactive Programming and FP, partically. I consider to use the Flux architecture instead of Elm's one.

Because it is very important to be simple for newbies to immerse and use the fastest, smallest and modular virtual DOM implementation. Don't dig yourself deeply under the FP. :-)

Flyd is wonderful __next__ step. Note that I've tried Beacon, RxJS and so on libs. They all are like **lodash** and **underscore** more than FRP in functional languages. They like stream processors. But observable state observed over time in 4 dimensions is wonderful aspect of FRP.

I advice you communicate with [Kris Koval](@kriskowal) on his [General Theory of Reactivity](https://github.com/kriskowal/gtor)!

**Comment by avesus** [comment] 2015-09-10 16:05
@ericgj,
> Deprecating the separate npm packages seems sane to me.

Ok, I think it is more healthier for __this__ project to have all _main modules_ in single npm package. Node's depends are pain.

**Comment by sindresorhus** [comment] 2015-09-10 16:09
> Ask @sindresorhus how to manage that most effectively!

Ask @jdalton. He does exactly this with Lodash.

**Comment by avesus** [comment] 2015-09-10 16:32
@sindresorhus, if I understand the things correclty, @jdalton splits the main `lodash.js` code into a bunch of small files with `lodash-cli`. I wonder if he really prefers to work with a single large file to do things. If that's true, then he prefers [Mithril](https://github.com/lhorie/mithril.js)' author's @lhorie approach to do things in a single file (see https://github.com/lodash/lodash/commit/307dae4facf7e8c8952a22a09958e3cc90893c8e for example).

Look @ `isModularize` in https://github.com/lodash/lodash-cli/blob/master/bin/lodash - he does really crazy sciense there. But newbies could learn how to effectively use lodash itself there :-)!.

**Comment by StreetStrider** [comment] 2015-09-10 16:59
lodash/lodash#1404

**Comment by jdalton** [comment] 2015-09-10 17:04
I like working with a single file then splitting it up, but that's just dev preference nonsense. The win is in modules. I recently discussed the `lodash/foo/bar` and `lodash.*` approached [here](https://github.com/lodash/lodash-cli/issues/44#issuecomment-139310803).

**Comment by jayrbolton** [comment] 2015-09-11 01:08
My vote is that functions like `filter`, `flatmap`, `every`, are core to FRP, inseparable from flyd, and you are almost guaranteed to need one or more of them for any flyd project. It makes a lot of sense to me that the core repo maintains the core modules. For all the more extraneous modules that are not core FRP functions and require extra dependencies, they can continue to be modules published separately in npm with separate repos named `flyd-modulename`

**Comment by iofjuupasli** [comment] 2015-09-11 10:17
Imagine that every method in each of your current dependency from project separated to its own module. You'll end with dependency hell. Bunch of modules in package.json that you should install, upgrade; huge number of `require('flyd-...')` through the project. Does it really better for code base?

In compare with lodash - lodash is *utils* at most. So it makes sence sometimes to depend only on one method you need for small project, especially for front-end. It's not so true for flyd.

It's from user side.

From maintainer pov - separating to many modules actually will add headache. After proper setup it will be leveled, but anyway it adds complexity to project maintaining, including entry threshold for new developers.

If someone want to create another one method - it's still possible to create fork, or module independent from mainteiner.

**Closed** 2016-03-25 07:01 UTC
